### ISSUE TITLE
AUC unusally high during 1st few epochs

### ISSUE THREAD

**Issue by bmabir17** [nuclearboy95/Anomaly-Detection-PatchSVDD-PyTorch#11]
I am training custom object class using my own dataset converted into MvTec Ad format. I am using small lambda value in the results below but its still the same for large lambda values. 
![Screenshot from 2021-03-17 11-58-40](https://user-images.githubusercontent.com/5344072/111422134-647fe400-8718-11eb-8b31-3230afaa5042.png)
Epochs: 300
Embedding dimension: 64

Can anyone tell me why this is happening?
I have also trained 'screw` class and the AUC is high only on 1st epoch and then it goes down drastically.

**Comment by MuchmorePatience** [comment]
Hi,I'm facing the problem that there is no 'rvai.types' moudle in mvtecad.py,Could u give me a hand?

> from rvai.types import String, Image

> Traceback (most recent call last):
  File "main_train.py", line 3, in <module>
    from codes import mvtecad
  File "C:\Users\CCone\Desktop\experiment0506\Patch_SVDD-master\codes\mvtecad.py", line 7, in <module>
    from rvai.types import String, Image
ModuleNotFoundError: No module named 'rvai'

**Comment by bmabir17** [comment]
@MuchmorePatience this is not related to this issue and i have not faced it. Maybe its a because my development environment is linux. Please check if the package requirements are met properly.

**Comment by MuchmorePatience** [comment]
Thanks a lot !

**Comment by MuchmorePatience** [comment]
@bmabir17 Anyway thanks a lot !

**Comment by Jiejiegary** [comment]
Hello, guys. I face the similar problem. It seems lamda matters. Can anyone provide optimal lamda for each class?

**Comment by MuchmorePatience** [comment]
@bmabir17 Hi ,I'm coming again. I failed to understand the 'ground_truth' pictures for what ? Waiting for your reply!
